// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq2ro8T8KOuM6ROscYKRoFY6XZ2YuaVB8',
    appId: '1:216120517954:web:04b452fe981161512714db',
    messagingSenderId: '216120517954',
    projectId: 'portfolio-bc130',
    authDomain: 'portfolio-bc130.firebaseapp.com',
    storageBucket: 'portfolio-bc130.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbPkXQ3TLtil4WqIMpxUrNh7JBV-3ZXjM',
    appId: '1:216120517954:android:9302e3632ca7ad752714db',
    messagingSenderId: '216120517954',
    projectId: 'portfolio-bc130',
    storageBucket: 'portfolio-bc130.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAkssBUzsg8jnTZiQ6gy5EiFCKbP6UuBQ',
    appId: '1:216120517954:ios:4e0a6841e436c0db2714db',
    messagingSenderId: '216120517954',
    projectId: 'portfolio-bc130',
    storageBucket: 'portfolio-bc130.firebasestorage.app',
    iosBundleId: 'anycar.com.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAkssBUzsg8jnTZiQ6gy5EiFCKbP6UuBQ',
    appId: '1:216120517954:ios:4e0a6841e436c0db2714db',
    messagingSenderId: '216120517954',
    projectId: 'portfolio-bc130',
    storageBucket: 'portfolio-bc130.firebasestorage.app',
    iosBundleId: 'anycar.com.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq2ro8T8KOuM6ROscYKRoFY6XZ2YuaVB8',
    appId: '1:216120517954:web:49a44df06e7d0b6a2714db',
    messagingSenderId: '216120517954',
    projectId: 'portfolio-bc130',
    authDomain: 'portfolio-bc130.firebaseapp.com',
    storageBucket: 'portfolio-bc130.firebasestorage.app',
  );
}
